[project]
name = "secrets-generator-util"
version = "0.1.0"
description = "cli app for generating secrets"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=6.16.0",
]
